name: Run Unit Test

on:
  pull_request:
    branches: [master, development]
  
jobs:
  test:
    name: Run Unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
          uses: actions/checkout@v3.3.0

      - name: Setup Java JDK
          uses: actions/setup-java@v3.10.0
          with:
            distribution: 'temurin'
            java-version: 17

      - name: Note App Unit test
          run: bash ./gradlew test